baseURL = 'https://lauristonrunners.club/'
languageCode = 'en-us'
title = 'Lauriston Runners'
theme = "ananke"

[params]
  custom_css = ["css/_font-awesome.css"]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Website for lauristonrunners.club"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/img/kent.png"
  recent_posts_number = 3
  cover_dimming_class = "bg-black"
  site_logo = "img/hwac.png"
  body_classes = "sans-serif bg-near-white"

[menu]
[[menu.main]]
  name = 'Home'
  # pre = "<i class='fa fa-heart'></i>"
  url = '/'
  weight = -110
[[menu.main]]
  name = 'News'
  # pre = "<i class='fa fa-heart'></i>"
  url = '/posts/'
  weight = -110
[[menu.main]]
  name = 'History'
  # post = "<span class='alert'>New!</span>"
  # pre = "<i class='fa fa-road'></i>"
  url = '/history/'
  weight = -100
[[menu.main]]
  name = 'About'
  # post = "<span class='alert'>New!</span>"
  # pre = "<i class='fa fa-road'></i>"
  url = '/about/'
  weight = -100
[[menu.main]]
  name = 'Join'
  # post = "<span class='alert'>New!</span>"
  # pre = "<i class='fa fa-road'></i>"
  url = '/join/'
  weight = -100
[[menu.main]]
  name = 'Kit'
  # post = "<span class='alert'>New!</span>"
  # pre = "<i class='fa fa-road'></i>"
  url = '/kit/'
  weight = -100
[[menu.main]]
  name = 'Contact'
  # post = "<span class='alert'>New!</span>"
  # pre = "<i class='fa fa-road'></i>"
  url = '/contact/'
  weight = -100
[[menu.main]]
  name = 'Fixtures'
  # post = "<span class='alert'>New!</span>"
  # pre = "<i class='fa fa-road'></i>"
  url = '/fixtures/'
  weight = -100
